autoload :Generator, 'rested_db/generator'
autoload :Builder, 'builder'
autoload :ProjectSettings, 'rested_db/project_settings'
autoload :ERB, 'erb'
autoload :DataMapper, 'datamapper'
autoload :ServerManager, 'rested_db/server_manager'
autoload :Migration, 'rested_db/migration'