require 'datamapper'
require 'sinatra/base'
require 'rest_in_peace/rip_controller'
require 'active_support'
autoload :Generator, 'rest_in_peace/generator'
autoload :Builder, 'builder'
autoload :ProjectSettings, 'rest_in_peace/project_settings'
autoload :ERB, 'erb'
autoload :ServerManager, 'rest_in_peace/server_manager'
autoload :Migration, 'rest_in_peace/migration'