require 'datamapper'
require 'sinatra/base'
require 'rested_db/rested_controller'
autoload :Generator, 'rested_db/generator'
autoload :Builder, 'builder'
autoload :ProjectSettings, 'rested_db/project_settings'
autoload :ERB, 'erb'
autoload :ServerManager, 'rested_db/server_manager'
autoload :Migration, 'rested_db/migration'